services:
  api:
    build: ./server        
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend