# Generated by Django 4.2.2 on 2023-06-23 22:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vectoroverlay', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataUploader',
            new_name='UploadedData',
        ),
    ]
