# Generated by Django 4.2.2 on 2023-06-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectoroverlay', '0004_rename_datauploader_uploadeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddata',
            name='forcePlateNames',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
