# Generated by Django 4.2.2 on 2023-06-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectoroverlay', '0006_alter_uploadeddata_textfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddata',
            name='forcePlateNames',
            field=models.TextField(default=''),
        ),
    ]
