# Generated by Django 4.2.2 on 2023-06-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectoroverlay', '0007_alter_uploadeddata_forceplatenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddata',
            name='forcePlateNames',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
