# Generated by Django 3.2.20 on 2023-07-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectoroverlay', '0008_alter_uploadeddata_forceplatenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddata',
            name='forcePlateNames',
            field=models.JSONField(default=list),
        ),
    ]
