# Generated by Django 3.2.20 on 2023-08-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectoroverlay', '0010_auto_20230801_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddata',
            name='bodyWeight',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='flips',
            field=models.JSONField(default=list),
        ),
    ]
