# Generated by Django 3.2.20 on 2023-08-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectoroverlay', '0011_auto_20230823_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddata',
            name='mode',
            field=models.CharField(default='combime', max_length=10),
        ),
    ]
