# Generated by Django 3.2.20 on 2023-09-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectoroverlay', '0012_uploadeddata_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddata',
            name='forceThreshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='uploadeddata',
            name='mode',
            field=models.CharField(default='combine', max_length=10),
        ),
    ]
