# Generated by Django 3.2.20 on 2023-09-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectoroverlay', '0013_auto_20230926_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddata',
            name='view',
            field=models.CharField(default='fy', max_length=4),
        ),
    ]
